### ISSUE TITLE
librespot sporadic crashes with disabled audio cache 

### ISSUE THREAD

**Issue by vansoest** [badaix/snapcast#394]
I've to restart the Spotify Snapcast service every day. The server crashed also by long Drum and Bass tracks from a very long playlist.

I running two snapserver instances on my raspberry pi 2 with arch linux arm.

using librespot in version 1:583.03de235-1- built via AUR form master git. (Mon Apr 16 17:50:11 2018)
and snapcast 0.13.0-1. (Wed Mar 14 23:58:46 2018)

That is the systemd service for the librespot stuff:

**/etc/systemd/system/snapserver-spotify.service**
```
[Unit]
Description=Snapcast server
After=network-online.target
Requires=network-online.target
After=avahi-daemon.service
Requires=avahi-daemon.service

[Service]
EnvironmentFile=-/etc/default/snapserver-spotify
ExecStart=/usr/bin/nice -n -8 /usr/bin/snapserver $USER_OPTS $SNAPSERVER_OPTS
PIDFile=/var/run/snapserver/pid

[Install]
WantedBy=multi-user.target
```

and the environment file for the service:

**/etc/default/snapserver-spotify**
```
START_SNAPSERVER=true
USER_OPTS="--user snapserver:snapserver"
SNAPSERVER_OPTS="--port 5002 --controlPort 5003 -s 'spotify:///librespot?name=SnapcastSpotify&devicename=Snapcast&bitrate=320&disable-audio-cache=true'"
```

I've also disabled audio cache.

the crashlog from systemd journal:

```
2018-05-04 12-01-52 [Info] (SnapcastSpotify) INFO:librespot_playback::player: Loading track "Odyssey - Original Mix" with Spotify URI "spotify:track:0YXTvEZ1NuPcOLpNxpwvGF"
2018-05-04 12-01-53 [Info] (SnapcastSpotify) ERROR:librespot_core::channel: channel error: 2 1
2018-05-04 12-01-53 [Info] (SnapcastSpotify) thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ChannelError', libcore/result.rs:945:5
2018-05-04 12-01-53 [Info] (SnapcastSpotify) stack backtrace:
2018-05-04 12-01-54 [Info] (SnapcastSpotify) 0x8bec9b - <unknown>
2018-05-04 12-01-54 [Info] (SnapcastSpotify) 1:   0x8b8c2f - <unknown>
2018-05-04 12-01-54 [Info]    2:   0x8bd717 - <unknown>
2018-05-04 12-01-54 [Info]    3:   0x8bd32b - <unknown>
2018-05-04 12-01-54 [Info]    4:   0x8bdbbb - <unknown>
2018-05-04 12-01-54 [Info] (SnapcastSpotify) 5:   0x8bda1f - <unknown>
2018-05-04 12-01-54 [Info]    6:   0x8bd9a3 - <unknown>
2018-05-04 12-01-54 [Info]    7:   0x8bd93b - <unknown>
2018-05-04 12-01-54 [Info]    8:   0x90e803 - <unknown>
2018-05-04 12-01-54 [Info]    9:   0x4b4667 - <unknown>
2018-05-04 12-01-54 [Info]   10:   0x4af8d3 - <unknown>
2018-05-04 12-01-54 [Info]   11:   0x43c267 - <unknown>
2018-05-04 12-01-54 [Info]   12:   0x44e4cf - <unknown>
2018-05-04 12-01-54 [Info] (SnapcastSpotify) 13:   0x8cd083 - <unknown>
2018-05-04 12-01-54 [Info]   14:   0x45029f - <unknown>
2018-05-04 12-01-54 [Info]   15:   0x8c394f - <unknown>
2018-05-04 12-01-54 [Info] onStateChanged (SnapcastSpotify): 1
2018-05-04 12-51-15 [Info] (SnapcastSpotify) thread '
2018-05-04 12-51-15 [Info] (SnapcastSpotify) main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', libcore/result.rs:945:5
2018-05-04 12-51-15 [Info] stack backtrace:
2018-05-04 12-51-15 [Info]    0:
2018-05-04 12-51-15 [Info] (SnapcastSpotify) 0x8bec9b - <unknown>
2018-05-04 12-51-15 [Info]    1:   0x8b8c2f - <unknown>
2018-05-04 12-51-15 [Info]    2:   0x8bd717 - <unknown>
2018-05-04 12-51-15 [Info]    3:   0x8bd32b - <unknown>
2018-05-04 12-51-15 [Info]    4:   0x8bdbbb - <unknown>
2018-05-04 12-51-15 [Info]    5:   0x8bda1f - <unknown>
2018-05-04 12-51-15 [Info]    6:   0x8bd9a3 - <unknown>
2018-05-04 12-51-15 [Info] (SnapcastSpotify) 7:   0x8bd93b - <unknown>
2018-05-04 12-51-15 [Info]    8:   0x90e803 - <unknown>
2018-05-04 12-51-15 [Info]    9:   0x4b46f7 - <unknown>
2018-05-04 12-51-15 [Info]   10:   0x4ab43f - <unknown>
2018-05-04 12-51-15 [Info]   11:   0x471d9f - <unknown>
2018-05-04 12-51-15 [Info]   12:   0x47126f - <unknown>
2018-05-04 12-51-15 [Info]   13:   0x4705bb - <unknown>
2018-05-04 12-51-15 [Info]   14:   0x45540b - <unknown>
2018-05-04 12-51-15 [Info]   15:   0x4507bf - <unknown>
2018-05-04 12-51-15 [Info]   16:   0x447fef - <unknown>
2018-05-04 12-51-15 [Info]   17:   0x4506df - <unknown>
2018-05-04 12-51-15 [Info]   18:   0x43c3c3 - <unknown>
2018-05-04 12-51-15 [Info] (SnapcastSpotify) 19:   0x43ee4f - <unknown>
2018-05-04 12-51-15 [Info]   20:   0x43c4fb - <unknown>
2018-05-04 12-51-15 [Info]   21:   0x43c733 - <unknown>
2018-05-04 12-51-15 [Info]   22:   0x43a6cb - <unknown>
2018-05-04 12-51-15 [Info]   23:   0x43699b - <unknown>
2018-05-04 12-51-15 [Info]   24:   0x457197 - <unknown>
2018-05-04 12-51-15 [Info]   25:   0x446d2f - <unknown>
2018-05-04 12-51-15 [Info]   26:   0x8bd873 - <unknown>
2018-05-04 12-51-15 [Info]   27:   0x8cd083 - <unknown>
2018-05-04 12-51-15 [Info]   28:   0x8bdfe3 - <unknown>
2018-05-04 12-51-15 [Info]   29:   0x457d77 - main
2018-05-04 12-51-15 [Info]   30: 0x76d73a7f - __libc_start_main
2018-05-04 12-51-15 [Info] ERROR:librespot_playback::player: Player thread panicked!
2018-05-04 12-51-15 [Err] (PipeStream) Exception: end of file
2018-05-04 12-51-45 [Info] onStateChanged (SnapcastSpotify): 2
2018-05-04 12-51-45 [Info] (SnapcastSpotify) INFO:librespot: librespot 03de235 (2018-04-12). Built on 2018-04-16. Build ID: 8Yv7zvQB
2018-05-04 12-51-47 [Info] onStateChanged (SnapcastSpotify): 1
```

If I restart the service, it works without problems like:
```
2018-05-04 12-51-45 [Info] (SnapcastSpotify) INFO:librespot: librespot 03de235 (2018-04-12). Built on 2018-04-16. Build ID: 8Yv7zvQB
2018-05-04 12-51-47 [Info] onStateChanged (SnapcastSpotify): 1
2018-05-04 13-09-19 [Info] (SnapcastSpotify) INFO:librespot_core::session: Connecting to AP "gew1-accesspoint-b-slpb.ap.spotify.com:4070"
2018-05-04 13-09-19 [Info] (SnapcastSpotify) INFO:librespot_core::session: Authenticated as "sophie.vansoest" !
2018-05-04 13-09-19 [Info] (SnapcastSpotify) INFO:librespot_core::session: Country: "DE"
2018-05-04 13-09-19 [Info] (SnapcastSpotify) INFO:librespot_playback::player: Loading track "Without You" with Spotify URI "spotify:track:7kH0DdCmCEKsswSCkkflSE"
2018-05-04 13-09-20 [Info] (SnapcastSpotify) INFO:librespot_playback::player: Track "Without You" loaded
2018-05-04 13-09-20 [Info] metadata: <Without You>
2018-05-04 13-09-20 [Info] metadata={
2018-05-04 13-09-20 [Info]     "STREAM": "SnapcastSpotify",
2018-05-04 13-09-20 [Info]     "TITLE": "Without You"
2018-05-04 13-09-20 [Info] }
2018-05-04 13-09-20 [Info] onMetaChanged (SnapcastSpotify)
2018-05-04 13-09-20 [Info] onResync (SnapcastSpotify): 1.05346e+06ms
2018-05-04 13-09-20 [Info] onStateChanged (SnapcastSpotify): 2
```

waiting a few minutes, a few tracks crashed!
```
2018-05-04 13-11-36 [Info] (SnapcastSpotify) INFO:librespot_playback::player: Loading track "You Don't Deserve Me" with Spotify URI "spotify:track:6vBvvmt0D8DUNOsHy6JMih"
2018-05-04 13-11-38 [Info] (SnapcastSpotify) INFO:librespot_playback::player: Track "You Don't Deserve Me" loaded
2018-05-04 13-11-38 [Info] metadata: <You Don't Deserve Me>
2018-05-04 13-11-38 [Info] metadata={
2018-05-04 13-11-38 [Info]     "STREAM": "SnapcastSpotify",
2018-05-04 13-11-38 [Info]     "TITLE": "You Don't Deserve Me"
2018-05-04 13-11-38 [Info] }
2018-05-04 13-11-38 [Info] onMetaChanged (SnapcastSpotify)
2018-05-04 13-18-28 [Info] (SnapcastSpotify) INFO:librespot_playback::player: Loading track "Interstellar Flight - Original Mix" with Spotify URI "spotify:track:63M9qWHu5iTrAEScOtIuPG"
2018-05-04 13-18-29 [Info] (SnapcastSpotify) INFO:librespot_playback::player: Track "Interstellar Flight - Original Mix" loaded
2018-05-04 13-18-29 [Info] metadata: <Interstellar Flight - Original Mix>
2018-05-04 13-18-29 [Info] metadata={
2018-05-04 13-18-29 [Info]     "STREAM": "SnapcastSpotify",
2018-05-04 13-18-29 [Info]     "TITLE": "Interstellar Flight - Original Mix"
2018-05-04 13-18-29 [Info] }
2018-05-04 13-18-29 [Info] onMetaChanged (SnapcastSpotify)
2018-05-04 13-25-28 [Info] (SnapcastSpotify) INFO:librespot_playback::player: Loading track "Found You" with Spotify URI "spotify:track:0yMkydm8a4mk7Eay1mwiz8"
2018-05-04 13-25-28 [Info] (SnapcastSpotify) ERROR:librespot_core::channel: channel error: 2 1
2018-05-04 13-25-28 [Info] (SnapcastSpotify) thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ChannelError', libcore/result.rs:945:5
2018-05-04 13-25-28 [Info] (SnapcastSpotify) stack backtrace:
2018-05-04 13-25-29 [Info] (SnapcastSpotify) 0:   0x991c9b - <unknown>
2018-05-04 13-25-29 [Info] (SnapcastSpotify) 1:   0x98bc2f - <unknown>
2018-05-04 13-25-29 [Info]    2:   0x990717 - <unknown>
2018-05-04 13-25-29 [Info]    3:   0x99032b - <unknown>
2018-05-04 13-25-29 [Info]    4:   0x990bbb - <unknown>
2018-05-04 13-25-29 [Info]    5
2018-05-04 13-25-29 [Info] (SnapcastSpotify) :   0x990a1f - <unknown>
2018-05-04 13-25-29 [Info]    6:   0x9909a3 - <unknown>
2018-05-04 13-25-29 [Info]    7:   0x99093b - <unknown>
2018-05-04 13-25-29 [Info]    8:   0x9e1803 - <unknown>
2018-05-04 13-25-29 [Info]    9:   0x587667 - <unknown>
2018-05-04 13-25-29 [Info]   10:   0x5828d3 - <unknown>
2018-05-04 13-25-29 [Info]   11:   0x50f267 - <unknown>
2018-05-04 13-25-29 [Info]   12:   0x5214cf - <unknown>
2018-05-04 13-25-29 [Info]   13:   0x
2018-05-04 13-25-29 [Info] (SnapcastSpotify) 9a0083 - <unknown>
2018-05-04 13-25-29 [Info]   14:   0x52329f - <unknown>
2018-05-04 13-25-29 [Info]   15:   0x99694f - <unknown>
2018-05-04 13-25-30 [Info] onStateChanged (SnapcastSpotify): 1
```

**Comment by praul** [comment]
It's a librespot problem that can only fixed by now when compiling librespot from source with rustup nightly
See https://github.com/librespot-org/librespot/issues/223
