### ISSUE TITLE
Librespot not found

### ISSUE THREAD

**Issue by lukasdietz** [badaix/snapcast#884]
**Describe the bug**
After running fine for a couple of weeks my Snapcast instance suddenly stopped working.
Snapserver constantly throws an error: `Connect exception: librespot not found`

**Steps to Reproduce**
1. Install Snapserver
2. Install Librespot using `cargo install librespot`
3. Add `stream = librespot:///librespot?name=Spotify&username=<USERNAME>&password=<PASSWORD>$gxs&devicename=Snapcast&bitrate=320&nomalize=true&autoplay=false` unter [stream] in /etc/snapserver.conf
4. restart snapserver service

**Environment details**
- OS: Debian 10 Buster (As LXC on a Proxmox host)
- Snapcast version: snapserver v0.24.0 (rev 7eff45fd)
- Installed latest stable release as debian package

**Attach logfile if applicable**
Generate logs with `snapclient --logfilter debug` or `snapserver --logging.filter debug` if possible and paste them in the following codeblock

```log
2021-05-26 10-42-44.832 [Info] (LibrespotStream) (Spotify[) [2021-05-26T10:42:44Z INFO  librespot] librespot 0.2.0 UNKNOWN (Built on 2021-05-26, Build ID: FooKApaN)
2021-05-26 10-42-44.832 [Info] (LibrespotStream) (Spotify[) thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-0.2.0/src/main.rs:463:48
2021-05-26 10-42-44.832 [Info] (LibrespotStream) (Spotify[) stack backtrace:
2021-05-26 10-42-44.842 [Info] (LibrespotStream) (Spotify[)    0:     0x56411a70e290 - std::backtrace_rs::backtrace::libunwind::trace::h5e9d00f0cdf4f57e
2021-05-26 10-42-44.843 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
2021-05-26 10-42-44.843 [Info] (LibrespotStream) (Spotify[)    1:     0x56411a70e290 - std::backtrace_rs::backtrace::trace_unsynchronized::hd5302bd66215dab9
2021-05-26 10-42-44.844 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
2021-05-26 10-42-44.844 [Info] (LibrespotStream) (Spotify[)    2:     0x56411a70e290 - std::sys_common::backtrace::_print_fmt::ha0237cd11a34e2bf
2021-05-26 10-42-44.845 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
2021-05-26 10-42-44.845 [Info] (LibrespotStream) (Spotify[)    3:     0x56411a70e290 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h171d4c10df1a98ee
2021-05-26 10-42-44.846 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
2021-05-26 10-42-44.849 [Info] (LibrespotStream) (Spotify[)    4:     0x56411a7330ec - core::fmt::write::h89e4288724daa3fa
2021-05-26 10-42-44.850 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
2021-05-26 10-42-44.850 [Info] (LibrespotStream) (Spotify[)    5:     0x56411a706a52 - std::io::Write::write_fmt::h6d40f996e84584d9
2021-05-26 10-42-44.851 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
2021-05-26 10-42-44.851 [Info] (LibrespotStream) (Spotify[)    6:     0x56411a710725 - std::sys_common::backtrace::_print::h0c0b93221682afc8
2021-05-26 10-42-44.852 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
2021-05-26 10-42-44.852 [Info] (LibrespotStream) (Spotify[)    7:     0x56411a710725 - std::sys_common::backtrace::print::h57a9f95204c2fdd6
2021-05-26 10-42-44.853 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
2021-05-26 10-42-44.853 [Info] (LibrespotStream) (Spotify[)    8:     0x56411a710725 - std::panicking::default_hook::{{closure}}::h4245258b50e37e69
2021-05-26 10-42-44.854 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
2021-05-26 10-42-44.854 [Info] (LibrespotStream) (Spotify[)    9:     0x56411a710283 - std::panicking::default_hook::h7b00dcc1d0944747
2021-05-26 10-42-44.855 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:225:9
2021-05-26 10-42-44.855 [Info] (LibrespotStream) (Spotify[)   10:     0x56411a710ec1 - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
2021-05-26 10-42-44.855 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:591:17
2021-05-26 10-42-44.856 [Info] (LibrespotStream) (Spotify[)   11:     0x56411a710a07 - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
2021-05-26 10-42-44.856 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
2021-05-26 10-42-44.857 [Info] (LibrespotStream) (Spotify[)   12:     0x56411a70e72c - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
2021-05-26 10-42-44.857 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
2021-05-26 10-42-44.858 [Info] (LibrespotStream) (Spotify[)   13:     0x56411a710969 - rust_begin_unwind
2021-05-26 10-42-44.858 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
2021-05-26 10-42-44.859 [Info] (LibrespotStream) (Spotify[)   14:     0x56411a730861 - core::panicking::panic_fmt::hcd56f7f635f62c74
2021-05-26 10-42-44.859 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
2021-05-26 10-42-44.859 [Info] (LibrespotStream) (Spotify[)   15:     0x56411a730683 - core::option::expect_none_failed::hf37eebedadde29e6
2021-05-26 10-42-44.860 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
2021-05-26 10-42-44.860 [Info] (LibrespotStream) (Spotify[)   16:     0x56411a2e5cfd - librespot::get_setup::h5735d0037833eed2
2021-05-26 10-42-44.861 [Info] (LibrespotStream) (Spotify[)   17:     0x56411a33c3fa - librespot::main::{{closure}}::hf174eb5dadaa6a1e
2021-05-26 10-42-44.861 [Info] (LibrespotStream) (Spotify[)   18:     0x56411a2faf67 - tokio::macros::scoped_tls::ScopedKey<T>::set::h5afe8179ff76e611
2021-05-26 10-42-44.862 [Info] (LibrespotStream) (Spotify[)   19:     0x56411a2de44f - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::h0468d0126abaf00b
2021-05-26 10-42-44.862 [Info] (LibrespotStream) (Spotify[)   20:     0x56411a2fbaeb - tokio::runtime::Runtime::block_on::h21c5ac6de7a02619
2021-05-26 10-42-44.863 [Info] (LibrespotStream) (Spotify[)   21:     0x56411a2e67a0 - librespot::main::hfa2dab2558bf6cc3
2021-05-26 10-42-44.863 [Info] (LibrespotStream) (Spotify[)   22:     0x56411a310673 - std::sys_common::backtrace::__rust_begin_short_backtrace::heea75a7113230c2d
2021-05-26 10-42-44.863 [Info] (LibrespotStream) (Spotify[)   23:     0x56411a3776b9 - std::rt::lang_start::{{closure}}::h0bed97e3334e6172
2021-05-26 10-42-44.864 [Info] (LibrespotStream) (Spotify[)   24:     0x56411a7113d7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h527fb2333ede305e
2021-05-26 10-42-44.865 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:259:13
2021-05-26 10-42-44.865 [Info] (LibrespotStream) (Spotify[)   25:     0x56411a7113d7 - std::panicking::try::do_call::h309d8aee8149866c
2021-05-26 10-42-44.866 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379:40
2021-05-26 10-42-44.866 [Info] (LibrespotStream) (Spotify[)   26:     0x56411a7113d7 - std::panicking::try::h75a60c31fd16bfc6
2021-05-26 10-42-44.867 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343:19
2021-05-26 10-42-44.867 [Info] (LibrespotStream) (Spotify[)   27:     0x56411a7113d7 - std::panic::catch_unwind::h1f9892423e99bc00
2021-05-26 10-42-44.867 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431:14
2021-05-26 10-42-44.868 [Info] (LibrespotStream) (Spotify[)   28:     0x56411a7113d7 - std::rt::lang_start_internal::hd5b67df56ca01dae
2021-05-26 10-42-44.868 [Info] (LibrespotStream) (Spotify[)                                at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/rt.rs:51:25
2021-05-26 10-42-44.868 [Info] (LibrespotStream) (Spotify[)   29:     0x56411a2e6862 - main
2021-05-26 10-42-44.869 [Info] (LibrespotStream) (Spotify[)   30:     0x7f918158509b - __libc_start_main
2021-05-26 10-42-44.869 [Info] (LibrespotStream) (Spotify[)   31:     0x56411a2ce0ca - _start
2021-05-26 10-42-44.870 [Info] (LibrespotStream) (Spotify[)   32:                0x0 - <unknown>
2021-05-26 10-42-44.871 [Error] (ProcessStream) Error while reading from stderr: End of file
2021-05-26 10-42-44.992 [Info] (Watchdog) Starting watchdog, timeout: 7800s
```

This Block repeats constantly!

Hope there is someone to help me out. I am confused because the setup stopped working without me changing something.

With best regards
Lukas

**Comment by badaix** [comment]
Looks like you're librespot is crashing. Have you tried starting it manually?

**Comment by badaix** [comment]
Nevermind, feel free to close the issue and to star the project

**Comment by lukasdietz** [comment]
Now my problem has changed a bit. 
I got help with my librespot problem. It starts now and connects with Spotify. If I start the service it throws the same error as before `Connect exception: librespot not found`. But if I run with `snapclient --logfilter debug` it starts without problems and connects fine but without any client playing sound. I am not sure what I am doing wrong now.

**Comment by kingosticks** [comment]
> But if I run with snapclient --logfilter debug

Do you mean snapserver here?

Have you tried using the snapserver service file without your custom modifications? `--server.datadir=${HOME}` will not work, use `%h` as per systemd docs.

**Comment by lukasdietz** [comment]
> Do you mean snapserver here?
Yes, I forgot to change it.


I used the service file from snapcast/debian/snapserver.service :

```
[Unit]
Description=Snapcast server
Documentation=man:snapserver(1)
Wants=avahi-daemon.service
After=network.target time-sync.target avahi-daemon.service

[Service]
EnvironmentFile=-/etc/default/snapserver
ExecStart=/usr/bin/snapserver --logging.sink=system --server.datadir=${HOME} $SNAPSERVER_OPTS
User=snapserver
Group=snapserver
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

I have tried using `ExecStart=/usr/bin/snapserver --logging.sink=system --server.datadir=%h $SNAPSERVER_OPTS` without success.

**Comment by badaix** [comment]
Thanks @kingosticks for your support
@lukasdietz please close a ticket when it is solved.
