### ISSUE TITLE
Unable to start librespot via snapcast

### ISSUE THREAD

**Issue by baschi29** [badaix/snapcast#967]
**Describe the bug**
I'm trying to use librespot as the sound source for snapcast. I'm running snapcast on a Raspberry pi 3. On my raspberry starting librespot normally did not work. I then tried the solution from this issue: https://github.com/librespot-org/librespot/issues/760 as I had the same error message. I now can start librespot manually from the command line, but trying to include

> [&params=--backend%20alsa]

leads to the following librespot error:

> Error parsing command line options: Option 'backend' given more than once

**Steps to Reproduce**
1. Install snapserver 0.26 and librespot 0.3.1
2. Add source into config

> source = librespot:///librespot?name=KartoffelbreiMusik[&dryout_ms=2000][&username='xxx'&password='xxx'][&devicename=Snapcast][&bitrate=320][&wd_timeout=7800][&volume=100][&onevent=""][&normalize=false][&autoplay=true][&cache=""][&disable_audio_cache=false][&killall=false][&params=--backend%20alsa]

3. Try starting snapserver

**Environment details**
- OS: Raspbian 11
- Snapcast version 0.26.0
- Installed from a package
- librespot 0.3.1, built via cargo

**Attach logfile if applicable**
Generate logs with `snapclient --logfilter debug` or `snapserver --logging.filter debug` if possible and paste them in the following codeblock

```log
2022-01-03 16-05-49.222 [Info] (Snapserver) Version 0.26.0, revision e30a9f33
2022-01-03 16-05-49.222 [Info] (Snapserver) Adding source: librespot:///librespot?name=KartoffelbreiMusik[&dryout_ms=2000][&username='xxx'&password='xxx'][&devicename=Snapcast][&bitrate=320][&wd_timeout=7800][&volume=100][&onevent=""][&normalize=false][&autoplay=true][&cache=""][&disable_audio_cache=false][&killall=false][&params=--backend%20alsa]
2022-01-03 16-05-49.223 [Notice] (init) Settings file: "/home/sound/.config/snapserver/server.json"
2022-01-03 16-05-49.223 [Info] (Snapserver) Using HTTP host name: raspberrypi
2022-01-03 16-05-49.233 [Info] (Avahi) Adding service 'Snapcast'
2022-01-03 16-05-49.242 [Debug] (parse) StreamUri: librespot:///librespot?name=KartoffelbreiMusik[&dryout_ms=2000][&username='xxx'&password='xxx'][&devicename=Snapcast][&bitrate=320][&wd_timeout=7800][&volume=100][&onevent=""][&normalize=false][&autoplay=true][&cache=""][&disable_audio_cache=false][&killall=false][&params=--backend%20alsa]
2022-01-03 16-05-49.244 [Debug] (parse) StreamUri.toString: librespot:////librespot?autoplay=true][&bitrate=320][&cache=""][&devicename=Snapcast][&disable_audio_cache=false][&dryout_ms=2000][&killall=false][&name=KartoffelbreiMusik[&normalize=false][&onevent=""][&params=--backend alsa]&password='xxx'][&username='xxx'&volume=100][&wd_timeout=7800][
2022-01-03 16-05-49.244 [Info] (PcmStream) PcmStream: KartoffelbreiMusik[, sampleFormat: 44100:16:2
2022-01-03 16-05-49.244 [Debug] (AsioStream) Chunk duration: 20 ms, frames: 882, size: 3528
2022-01-03 16-05-49.245 [Debug] (ProcessStream) Watchdog timeout: 7800
2022-01-03 16-05-49.245 [Info] (Server) Stream: {"fragment":"","host":"","path":"/librespot","query":{"autoplay":"true][","bitrate":"320][","cache":"\"\"][","chunk_ms":"20","codec":"flac","devicename":"Snapcast][","disable_audio_cache":"false][","dryout_ms":"2000][","killall":"false][","name":"KartoffelbreiMusik[","normalize":"false][","onevent":"\"\"][","params":"--backend alsa]","password":"xxx","sampleformat":"44100:16:2","username":"xxx","volume":"100][","wd_timeout":"7800]["},"raw":"librespot:////librespot?autoplay=true][&bitrate=320][&cache=\"\"][&chunk_ms=20&codec=flac&devicename=Snapcast][&disable_audio_cache=false][&dryout_ms=2000][&killall=false][&name=KartoffelbreiMusik[&normalize=false][&onevent=\"\"][&params=--backend alsa]&password=xxx&sampleformat=44100:16:2&username=xxx&volume=100][&wd_timeout=7800][","scheme":"librespot"}
2022-01-03 16-05-49.245 [Debug] (parse) StreamUri: librespot:///librespot?name=KartoffelbreiMusik[&dryout_ms=2000][&username='xxx'][&devicename=Snapcast][&bitrate=320][&wd_timeout=7800][&volume=100][&onevent=""][&normalize=false][&autoplay=true][&cache=""][&disable_audio_cache=false][&killall=false][&params=--backend%20alsa]
2022-01-03 16-05-49.247 [Debug] (parse) StreamUri.toString: librespot:////librespot?autoplay=true][&bitrate=320][&cache=""][&devicename=Snapcast][&disable_audio_cache=false][&dryout_ms=2000][&killall=false][&name=KartoffelbreiMusik[&normalize=false][&onevent=""][&params=--backend alsa]&password='xxx'][&username='xxx'&volume=100][&wd_timeout=7800][
2022-01-03 16-05-49.247 [Debug] (PcmStream) Start: KartoffelbreiMusik[, type: librespot, sampleformat: 44100:16:2, codec: flac
2022-01-03 16-05-49.247 [Info] (FlacEnc) Init - compression level: 2
2022-01-03 16-05-49.255 [Debug] (ProcessStream) Launching: '/home/sound/.cargo/bin/librespot', with params: '--backend alsa] --name "Snapcast][" --username "'xxx'" --password "'xxx'][" --bitrate 320][ --backend pipe --cache """][" --initial-volume 100][ --onevent """][" --verbose', in path: '/home/sound/.cargo/bin/'
2022-01-03 16-05-49.259 [Info] (Watchdog) Starting watchdog, timeout: 7800s
2022-01-03 16-05-49.259 [Info] (ControlServer) Creating TCP acceptor for address: 0.0.0.0, port: 1705
2022-01-03 16-05-49.260 [Info] (ControlServer) Creating HTTP acceptor for address: 0.0.0.0, port: 1780
2022-01-03 16-05-49.260 [Info] (StreamServer) Creating stream acceptor for address: 0.0.0.0, port: 1704
2022-01-03 16-05-49.260 [Info] (Snapserver) Number of threads: 4, hw threads: 4
2022-01-03 16-05-49.270 [Info] (LibrespotStream) (KartoffelbreiMusik[) Error parsing command line options: Option 'backend' given more than once
2022-01-03 16-05-49.271 [Info] (LibrespotStream) (KartoffelbreiMusik[) Usage: /home/sound/.cargo/bin/librespot [options]
```

**Edit:**
Alright, as it seems snapserver needs to use the pipe backend of librespot and sets it automatically, which explains the error. Maybe that could be mentioned in the documentation?

Anyway, without the additional parameter, librespot still crashes when started by snapserver:

```
2022-01-03 18-16-13.464 [Info] (Snapserver) Version 0.26.0, revision e30a9f33
2022-01-03 18-16-13.465 [Info] (Snapserver) Adding source: librespot:///librespot?name=Spotify[&dryout_ms=2000][&username=xxx&password=xxx][&devicename=Snapcast][&bitrate=320][&wd_timeout=7800][&volume=100][&onevent=""][&normalize=false][&autoplay=true][&cache=""][&disable_audio_cache=false][&killall=false][&params=]
2022-01-03 18-16-13.465 [Notice] (init) Settings file: "/home/sound/.config/snapserver/server.json"
2022-01-03 18-16-13.466 [Info] (Snapserver) Using HTTP host name: raspberrypi
2022-01-03 18-16-13.480 [Info] (Avahi) Adding service 'Snapcast'
2022-01-03 18-16-13.492 [Debug] (parse) StreamUri: librespot:///librespot?name=Spotify[&dryout_ms=2000][&username=xxx&password=xxx][&devicename=Snapcast][&bitrate=320][&wd_timeout=7800][&volume=100][&onevent=""][&normalize=false][&autoplay=true][&cache=""][&disable_audio_cache=false][&killall=false][&params=]
2022-01-03 18-16-13.494 [Debug] (parse) StreamUri.toString: librespot:////librespot?autoplay=true][&bitrate=320][&cache=""][&devicename=Snapcast][&disable_audio_cache=false][&dryout_ms=2000][&killall=false][&name=Spotify[&normalize=false][&onevent=""][&params=]&password=xxx][&username=xxx&volume=100][&wd_timeout=7800][
2022-01-03 18-16-13.495 [Info] (PcmStream) PcmStream: Spotify[, sampleFormat: 44100:16:2
2022-01-03 18-16-13.495 [Debug] (AsioStream) Chunk duration: 20 ms, frames: 882, size: 3528
2022-01-03 18-16-13.495 [Debug] (ProcessStream) Watchdog timeout: 7800
2022-01-03 18-16-13.495 [Info] (Server) Stream: {"fragment":"","host":"","path":"/librespot","query":{"autoplay":"true][","bitrate":"320][","cache":"\"\"][","chunk_ms":"20","codec":"flac","devicename":"Snapcast][","disable_audio_cache":"false][","dryout_ms":"2000][","killall":"false][","name":"Spotify[","normalize":"false][","onevent":"\"\"][","params":"]","password":"xxx","sampleformat":"44100:16:2","username":"xxx","volume":"100][","wd_timeout":"7800]["},"raw":"librespot:////librespot?autoplay=true][&bitrate=320][&cache=\"\"][&chunk_ms=20&codec=flac&devicename=Snapcast][&disable_audio_cache=false][&dryout_ms=2000][&killall=false][&name=Spotify[&normalize=false][&onevent=\"\"][&params=]&password=xxx&sampleformat=44100:16:2&username=xxx&volume=100][&wd_timeout=7800][","scheme":"librespot"}
2022-01-03 18-16-13.496 [Debug] (parse) StreamUri: librespot:///librespot?name=Spotify[&dryout_ms=2000][&username=xxx&password=xxx][&devicename=Snapcast][&bitrate=320][&wd_timeout=7800][&volume=100][&onevent=""][&normalize=false][&autoplay=true][&cache=""][&disable_audio_cache=false][&killall=false][&params=]
2022-01-03 18-16-13.497 [Debug] (parse) StreamUri.toString: librespot:////librespot?autoplay=true][&bitrate=320][&cache=""][&devicename=Snapcast][&disable_audio_cache=false][&dryout_ms=2000][&killall=false][&name=Spotify[&normalize=false][&onevent=""][&params=]&password=xxx][&username=xxx&volume=100][&wd_timeout=7800][
2022-01-03 18-16-13.498 [Debug] (PcmStream) Start: Spotify[, type: librespot, sampleformat: 44100:16:2, codec: flac
2022-01-03 18-16-13.498 [Info] (FlacEnc) Init - compression level: 2
2022-01-03 18-16-13.509 [Debug] (ProcessStream) Launching: '/home/sound/.cargo/bin/librespot', with params: '] --name "Snapcast][" --username "xxx" --password "xxx][" --bitrate 320][ --backend pipe --cache """][" --initial-volume 100][ --onevent """][" --verbose', in path: '/home/sound/.cargo/bin/'
2022-01-03 18-16-13.514 [Info] (Watchdog) Starting watchdog, timeout: 7800s
2022-01-03 18-16-13.514 [Info] (ControlServer) Creating TCP acceptor for address: 0.0.0.0, port: 1705
2022-01-03 18-16-13.514 [Info] (ControlServer) Creating HTTP acceptor for address: 0.0.0.0, port: 1780
2022-01-03 18-16-13.514 [Info] (StreamServer) Creating stream acceptor for address: 0.0.0.0, port: 1704
2022-01-03 18-16-13.515 [Info] (Snapserver) Number of threads: 4, hw threads: 4
2022-01-03 18-16-13.529 [Info] (librespot) librespot 0.3.1 UNKNOWN (Built on 2022-01-03, Build ID: IQmK2DF8, Profile: release)
2022-01-03 18-16-13.531 [Debug] (librespot_playback::mixer::mappings) Volume control is now Log(60.0)
2022-01-03 18-16-13.532 [Info] (LibrespotStream) (Spotify[) thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', /home/sound/.cargo/registry/src/github.com-1285ae84e5963aae/librespot-0.3.1/src/main.rs:608:56
2022-01-03 18-16-13.532 [Info] (LibrespotStream) (Spotify[) stack backtrace:
2022-01-03 18-16-13.559 [Info] (LibrespotStream) (Spotify[)    0:   0x8e6b7c - std::backtrace_rs::backtrace::libunwind::trace::h69f9fd2714ce4bc2
2022-01-03 18-16-13.559 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
2022-01-03 18-16-13.559 [Info] (LibrespotStream) (Spotify[)    1:   0x8e6b7c - std::backtrace_rs::backtrace::trace_unsynchronized::h4a8e909513b6e06a
2022-01-03 18-16-13.559 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/std/src/../../backtrace/src/backtrace/mod.rs:66
2022-01-03 18-16-13.559 [Info] (LibrespotStream) (Spotify[)    2:   0x8e6b7c - std::sys_common::backtrace::_print_fmt::h52305d9416d00c83
2022-01-03 18-16-13.559 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/std/src/sys_common/backtrace.rs:79
2022-01-03 18-16-13.560 [Info] (LibrespotStream) (Spotify[)    3:   0x8e6b7c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7a6619d4202eef04
2022-01-03 18-16-13.560 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/std/src/sys_common/backtrace.rs:58
2022-01-03 18-16-13.562 [Info] (LibrespotStream) (Spotify[)    4:   0x92e708 - core::fmt::write::h888c0afceb02375c
2022-01-03 18-16-13.563 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/core/src/fmt/mod.rs:1080
2022-01-03 18-16-13.566 [Info] (LibrespotStream) (Spotify[)    5:   0x8e3e30 - std::io::Write::write_fmt::hf6a7f6f966cd960a
2022-01-03 18-16-13.566 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/std/src/io/mod.rs:1516
2022-01-03 18-16-13.573 [Info] (LibrespotStream) (Spotify[)    6:   0x907144 - std::sys_common::backtrace::_print::h018ade6e64e28e25
2022-01-03 18-16-13.574 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/std/src/sys_common/backtrace.rs:61
2022-01-03 18-16-13.574 [Info] (LibrespotStream) (Spotify[)    7:   0x907144 - std::sys_common::backtrace::print::haf9b5e7bdaf9a3d4
2022-01-03 18-16-13.575 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/std/src/sys_common/backtrace.rs:48
2022-01-03 18-16-13.575 [Info] (LibrespotStream) (Spotify[)    8:   0x907144 - std::panicking::default_hook::{{closure}}::h4440f0880e8f955e
2022-01-03 18-16-13.575 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:208
2022-01-03 18-16-13.575 [Info] (LibrespotStream) (Spotify[)    9:   0x906ddc - std::panicking::default_hook::h74094067c460383e
2022-01-03 18-16-13.575 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:227
2022-01-03 18-16-13.575 [Info] (LibrespotStream) (Spotify[)   10:   0x907758 - std::panicking::rust_panic_with_hook::h9a80e76d4d022c16
2022-01-03 18-16-13.576 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:577
2022-01-03 18-16-13.576 [Info] (LibrespotStream) (Spotify[)   11:   0x8e76ec - std::panicking::begin_panic_handler::{{closure}}::h111e82fe96df6eec
2022-01-03 18-16-13.576 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:484
2022-01-03 18-16-13.576 [Info] (LibrespotStream) (Spotify[)   12:   0x8e6ce0 - std::sys_common::backtrace::__rust_end_short_backtrace::h5780bf66f2132951
2022-01-03 18-16-13.576 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/std/src/sys_common/backtrace.rs:153
2022-01-03 18-16-13.577 [Info] (LibrespotStream) (Spotify[)   13:   0x90738c - rust_begin_unwind
2022-01-03 18-16-13.577 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:483
2022-01-03 18-16-13.578 [Info] (LibrespotStream) (Spotify[)   14:   0x92d090 - core::panicking::panic_fmt::h34eac029a1e6841c
2022-01-03 18-16-13.578 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/core/src/panicking.rs:85
2022-01-03 18-16-13.579 [Info] (LibrespotStream) (Spotify[)   15:   0x92d10c - core::result::unwrap_failed::h90fc99f4efeecb7c
2022-01-03 18-16-13.579 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/core/src/result.rs:1220
2022-01-03 18-16-13.579 [Info] (LibrespotStream) (Spotify[)   16:   0x463410 - librespot::get_setup::hdc661e52c1d1455e
2022-01-03 18-16-13.579 [Info] (LibrespotStream) (Spotify[)   17:   0x4c13ac - librespot::main::{{closure}}::hc9f53abac3d56110
2022-01-03 18-16-13.579 [Info] (LibrespotStream) (Spotify[)   18:   0x4938bc - tokio::macros::scoped_tls::ScopedKey<T>::set::habfc583dce1025dd
2022-01-03 18-16-13.579 [Info] (LibrespotStream) (Spotify[)   19:   0x512eac - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::hea64ee50f06e8fe9
2022-01-03 18-16-13.580 [Info] (LibrespotStream) (Spotify[)   20:   0x46d784 - tokio::runtime::Runtime::block_on::hfd2582d04b438d13
2022-01-03 18-16-13.580 [Info] (LibrespotStream) (Spotify[)   21:   0x463f84 - librespot::main::hdc793ed4f174641a
2022-01-03 18-16-13.580 [Info] (LibrespotStream) (Spotify[)   22:   0x48b694 - std::sys_common::backtrace::__rust_begin_short_backtrace::h29ed95324ce5c38f
2022-01-03 18-16-13.580 [Info] (LibrespotStream) (Spotify[)   23:   0x4fe354 - std::rt::lang_start::{{closure}}::h0733c01843986ac4
2022-01-03 18-16-13.581 [Info] (LibrespotStream) (Spotify[)   24:   0x907b14 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h06a67a527deb8867
2022-01-03 18-16-13.581 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/core/src/ops/function.rs:259
2022-01-03 18-16-13.581 [Info] (LibrespotStream) (Spotify[)   25:   0x907b14 - std::panicking::try::do_call::h68c7bbd90af1d0b0
2022-01-03 18-16-13.582 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:381
2022-01-03 18-16-13.582 [Info] (LibrespotStream) (Spotify[)   26:   0x907b14 - std::panicking::try::h9a7b8ebd5dbc2bd4
2022-01-03 18-16-13.582 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:345
2022-01-03 18-16-13.582 [Info] (LibrespotStream) (Spotify[)   27:   0x907b14 - std::panic::catch_unwind::hbfdab6471a24311a
2022-01-03 18-16-13.583 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/std/src/panic.rs:382
2022-01-03 18-16-13.583 [Info] (LibrespotStream) (Spotify[)   28:   0x907b14 - std::rt::lang_start_internal::hc86d6a13cf8cfe5d
2022-01-03 18-16-13.583 [Info] (LibrespotStream) (Spotify[)                        at /usr/src/rustc-1.48.0/library/std/src/rt.rs:51
2022-01-03 18-16-13.584 [Info] (LibrespotStream) (Spotify[)   29:   0x4640c0 - main
2022-01-03 18-16-13.584 [Info] (LibrespotStream) (Spotify[)   30: 0x76cacbe0 - __libc_start_main

```

I can however start a librespot session from the command line with the definded parameters perfectly fine:
```
librespot --name "Snapcast" --username "xxx" --password "xxx" --bitrate 320 --backend pipe --cache "" --initial-volume 100  --verbose

```
Maybe the argument parser isn't working correctly or I have an error in my .conf file? For comparison here the part from the snapcast log:
```
2022-01-03 18-16-13.509 [Debug] (ProcessStream) Launching: '/home/sound/.cargo/bin/librespot', with params: '] --name "Snapcast][" --username "xxx" --password "xxx][" --bitrate 320][ --backend pipe --cache """][" --initial-volume 100][ --onevent """][" --verbose', in path: '/home/sound/.cargo/bin/'
```

**Comment by atatdotdot** [comment]
You just pasted your real password, so you need to change it now!

**Comment by badaix** [comment]
You should remove the brackets in your config, as stated in [configuration.md](https://github.com/badaix/snapcast/blob/master/doc/configuration.md#sources):

> The following notation is used in this paragraph:
>  
> angle brackets: the whole expression must be replaced with your specific setting
> [square brackets]: the whole expression is optional and can be left out
> [key=value]: if you leave this option out, "value" will be the default for "key"

the brackets only say that the value is optional, as in [EBNF notation](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form).

**Comment by baschi29** [comment]
Oh well, I guess I kinda misunderstood that paragraph. Thanks!

On another note, it seems that librespot has issues with some special characters in the spotify password - I will open an Issue there.
