### ISSUE TITLE
Android app crashes on Nougat when changing volume

### ISSUE THREAD

**Issue by schrockblock** [badaix/snapcast#97]
Here's the stacktrace:

```
23:47:22.905 21792-21792/? D/TCP: Sending: {"jsonrpc":"2.0","method":"Client.SetVolume","id":1,"params":{"client":"00:0f:12:88:3c:32","volume":18}}
08-26 23:47:22.907 21792-21792/? E/InputEventReceiver: Exception dispatching input event.
08-26 23:47:22.907 21792-21792/? E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
08-26 23:47:22.914 21792-21792/? E/MessageQueue-JNI: android.os.NetworkOnMainThreadException
                                                         at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1303)
                                                         at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
                                                         at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
                                                         at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
                                                         at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
                                                         at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
                                                         at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
                                                         at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
                                                         at java.io.BufferedWriter.flush(BufferedWriter.java:254)
                                                         at java.io.PrintWriter.newLine(PrintWriter.java:482)
                                                         at java.io.PrintWriter.println(PrintWriter.java:629)
                                                         at java.io.PrintWriter.println(PrintWriter.java:740)
                                                         at de.badaix.snapcast.control.TcpClient.sendMessage(TcpClient.java:72)
                                                         at de.badaix.snapcast.control.RemoteControl.setVolume(RemoteControl.java:222)
                                                         at de.badaix.snapcast.MainActivity.onVolumeChanged(MainActivity.java:583)
                                                         at de.badaix.snapcast.ClientItem.onProgressChanged(ClientItem.java:93)
                                                         at android.widget.SeekBar.onProgressRefresh(SeekBar.java:93)
                                                         at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:1327)
                                                         at android.widget.ProgressBar.refreshProgress(ProgressBar.java:1382)
                                                         at android.widget.ProgressBar.setProgressInternal(ProgressBar.java:1447)
                                                         at android.widget.AbsSeekBar.trackTouchEvent(AbsSeekBar.java:850)
                                                         at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:778)
                                                         at android.view.View.dispatchTouchEvent(View.java:9939)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                         at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:411)
                                                     	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWin
08-26 23:47:22.915 21792-21792/? D/AndroidRuntime: Shutting down VM
08-26 23:47:22.916 21792-21792/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: de.badaix.snapcast, PID: 21792
                                                   android.os.NetworkOnMainThreadException
                                                       at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1303)
                                                       at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
                                                       at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
                                                       at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
                                                       at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
                                                       at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
                                                       at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
                                                       at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
                                                       at java.io.BufferedWriter.flush(BufferedWriter.java:254)
                                                       at java.io.PrintWriter.newLine(PrintWriter.java:482)
                                                       at java.io.PrintWriter.println(PrintWriter.java:629)
                                                       at java.io.PrintWriter.println(PrintWriter.java:740)
                                                       at de.badaix.snapcast.control.TcpClient.sendMessage(TcpClient.java:72)
                                                       at de.badaix.snapcast.control.RemoteControl.setVolume(RemoteControl.java:222)
                                                       at de.badaix.snapcast.MainActivity.onVolumeChanged(MainActivity.java:583)
                                                       at de.badaix.snapcast.ClientItem.onProgressChanged(ClientItem.java:93)
                                                       at android.widget.SeekBar.onProgressRefresh(SeekBar.java:93)
                                                       at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:1327)
                                                       at android.widget.ProgressBar.refreshProgress(ProgressBar.java:1382)
                                                       at android.widget.ProgressBar.setProgressInternal(ProgressBar.java:1447)
                                                       at android.widget.AbsSeekBar.trackTouchEvent(AbsSeekBar.java:850)
                                                       at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:778)
                                                       at android.view.View.dispatchTouchEvent(View.java:9939)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
08-26 23:47:22.916 21792-21792/? E/AndroidRuntime:     at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:411)
                                                       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
                                                       at android.view.View.dispatchPointerEvent(View.java:10159)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4434)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3995)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4052)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
                                                       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6210)
                                                       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6184)
                                                       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6145)
                                                       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6313)
                                                       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                       at android.os.MessageQueue.next(MessageQueue.java:323)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
08-26 23:47:22.921 4293-10378/? W/ActivityManager:   Force finishing activity de.badaix.snapcast/.MainActivity
```

**Comment by schrockblock** [comment]
#99 fixes this. Please close when merged.

**Comment by badaix** [comment]
merged :)
